"""currency code property added to Rate model

Revision ID: fa2361224619
Revises: 093b9debc273
Create Date: 2026-02-05 15:22:47.464749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2361224619'
down_revision: Union[str, Sequence[str], None] = '093b9debc273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates', sa.Column('currency_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_updates_id'), 'updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updates_id'), table_name='updates')
    op.drop_column('rates', 'currency_code')
    # ### end Alembic commands ###
